name: CI

on:
    pull_request:

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: '17'
                  cache: gradle
            - name: Setup ruby
              uses: actions/setup-ruby@v1
              with:
                  ruby-version: '3.1'
                  architecture: 'x64'
            - name: Cache Ruby gems
              uses: actions/cache@v3
              with:
                  path: vendor/bundle
                  key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-gems-
            - name: Install danger and Set Gradle properties
              run: |
                  gem install bundler
                  bundle install
                  echo "org.gradle.daemon=false" >> gradle.properties
            - name: Run checks
              run: |
                  ./gradlew ktlintCheck -Dorg.gradle.jvmargs=-Xmx2g
                  ./gradlew lintDevelopmentDebug -Dorg.gradle.jvmargs=-Xmx2g
                  ./gradlew testDevelopmentDebugUnitTest -Dorg.gradle.jvmargs=-Xmx2g
            - name: Run danger
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: danger
